import Navbar from "@/components/Navbar";
import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {/* Code goes here */}
<Navbar/>
        {/* hero section */}
        <div >
        
          <div className="navbar flex justify-center">
            <div className="nav_links">
             
            </div>
          </div>
        </div>

        <div className="mt-32 flex flex-col items-center justify-center">
          <p className="motto ">Studio | Metaverse| Academy</p>
          <h1 className="font-bold mt-6 text-center text-2xl">
            Keeping Pace With The Global Trends
          </h1>
          <button class="bg-yellow-500 mt-3 hover:bg-gray-400 text-white font-bold py-4 px-5 rounded inline-flex items-center">
            {/* <svg
              class="fill-current w-4 h-4 mr-2"
              xmlns="http://www.w3.org/2000/svg"
              viewBox="0 0 20 20"
            >
              <path d="M13 8V2H7v6H2l8 8 8-8h-5zM0 18h20v2H0v-2z" />
            </svg> */}
            <span>CONTACT US NOW</span>
          </button>
        </div>

        {/* info section */}

        {/* slider  */}

        {/* footer */}
      </div>
    </>
  );
}
