import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {/* Code goes here */}

        {/* hero section */}
        <div className="w-100 flex items-center my-5 mx-10">
          <div className="w-1/3">
            <img
              src="data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXwBFRcXHhoeOyEhO3xTRlN8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fP/AABEIAIIArgMBIgACEQEDEQH/xAAaAAEBAQEBAQEAAAAAAAAAAAAABAMCAQYF/8QAKxABAAICAQIEBgEFAAAAAAAAAAECAxEEEiETMUFRFCIyM2GRcTRSgqGx/8QAFQEBAQAAAAAAAAAAAAAAAAAAAAH/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwD60AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGXJ+xYHmTk0p2r80/hnrk5fm30+0eTLBmrin5qb/Mea2uSl43W0aBhXkzSenNXU+6itotG6zEwnzcjHMdMRF/8Ajjhfdt/ALE/j2+I8PUa3pQin+t/yBaDDk5pxxFa9rT6+wNxHOHPFevrnet633d4+TPg2m3e1f9gpEdIz5t3i8x37dymTJPIrW8z594BYJL5MmbL0Y51Dm0ZuPMTNtxP57AtHlLRekWj1h6AAAAAy5P2LNSYiY1PeAflC3JxK270npn2S2xXpbU1nfoo5b8L7s/w9x8S098k9Me3qqpjrjjVY0g6RWmI5m57RFlrG/Gpe82mZ3IO/Gxf3x+0vJmJyVvE7rrzhr8HT3s7jBTw+ie8eYOpyU8Ob7jWkNazOPJMeUaUfB139dv01mKYcU6rM1jzj3BnxclIxdMzETG/NlFovzImvlMva1495meqa/iZeYoi3Kjo+mAOPMY89ot29O7TmXr0RXcb3tpl49Ms7ncT7x6uKcSlZ3Mzb8A048TGCm/bbQAAAAAAAAAAAAAAAAAZTxsUz9P6l3THXH9EadAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/2Q=="
              alt="logo"
            />
          </div>
          <div className="navbar flex justify-center">
            <div className="nav_links">
              <ul className="flex space-x-6 justify-start">
                <li>Home</li>
                <li>Studios</li>
                <li>Metaverse</li>
                <li>Academy</li>
                <li>About</li>
                <li>Contacts</li>
              </ul>
            </div>
          </div>
        </div>

        <div className="hero_section"></div>

        {/* info section */}

        {/* slider  */}

        {/* footer */}
      </div>
    </>
  );
}
