import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {/* Code goes here */}

        {/* hero section */}
        <div className="w-100 flex items-center my-10 mx-20">
          <div className="w-1/3">
            <Image height={100} width={100} src="./next.svg" alt="logo" />
          </div>
          <div className="navbar flex justify-center">
            <div className="nav_links">
              <ul className="md:flex space-x-6 justify-start hidden ">
                <li>Home</li>
                <li>Studios</li>
                <li>Metaverse</li>
                <li>Academy</li>
                <li>About</li>
                <li>Contacts</li>
              </ul>
            </div>
          </div>
        </div>

        <div className="mt-32 flex flex-col items-center justify-center">
          <p className="motto ">Studio | Metaverse| Academy</p>
          <h1 className="font-bold mt-6 text-center text-2xl">
            Keeping Pace With The Global Trends
          </h1>
          <button class="bg-yellow-300 hover:bg-gray-400 text-white font-bold py-2 px-4 rounded inline-flex items-center">
            <svg
              class="fill-current w-4 h-4 mr-2"
              xmlns="http://www.w3.org/2000/svg"
              viewBox="0 0 20 20"
            >
              <path d="M13 8V2H7v6H2l8 8 8-8h-5zM0 18h20v2H0v-2z" />
            </svg>
            <span>CONTACT US</span>
          </button>
        </div>

        {/* info section */}

        {/* slider  */}

        {/* footer */}
      </div>
    </>
  );
}
